def sam_nambers(nam):
    print(nam, end='')
sam_nambers(8)
sam_nambers(8)
sam_nambers(0)
sam_nambers(0)
sam_nambers(5)
sam_nambers(5)
sam_nambers(5)
sam_nambers(3)
sam_nambers(5)
sam_nambers(3)
sam_nambers(5)